cart/urls.py
from django.urls import path 
from . import views




app_name='cart'



urlpatterns = [
    path('',views.cart_summery,name='cart_summery'),
    path('add/',views.cart_add,name='cart_add'),
    path('delete/<str:product_slug>',views.cart_delete,name='cart_delete'),
    path('update/',views.cart_update,name='cart_update'),
    
  

    
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("admin/", admin.site.urls),

    path("", include('store.urls', namespace='store') ),
    
    
]




urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.urls import reverse
from .cart import Cart
from product.models import Product
from django.http import JsonResponse
# Create your views here.



def cart_summery(request):
	# Get The Cart
	cart = Cart(request)
	cart_products = cart.get_prods()
	quantity = cart.get_quants()
	all_total_price = cart.get_all_total_prices()
	single_total_price = cart.get_single_total_price()
	#cart_update = cart.update()

	


	# print(quantity)
	# print(single_total_price)


	context = {'cart_products':cart_products,
	'quantity':quantity,
	'single_total_price':single_total_price,
	'all_total_price':all_total_price,
	# 'cart_update':cart_update
	
	}
	return render(request, 'cart_summery.html' , context)







def cart_add(request):
	# get the cart
	cart = Cart(request)
	#test for Post
	if request.POST.get('action') == 'post' :
		# Get Stuff
		product_slug = request.POST.get('product_slug')
		product_qty = int(request.POST.get('product_qty')) 

		# Lookup Product in DB
		product = get_object_or_404(Product, PRDSlug=product_slug)

		# save to session 
		cart.add(product=product,quantity=product_qty)

		print('Product Name :',product.PRDName)

		# Get Cart Quantity
		cart_quantity = cart.__len__()
		# Return Response
		#response = JsonResponse({'Product Name':product.PRDName , 'Price':product.PRDPrice})
		
		response = JsonResponse({'qty':cart_quantity})
		return response








def cart_delete(request, product_slug):
    cart = Cart(request)
    cart.remove(product_slug)
    return redirect(reverse('cart:cart_summery'))








def cart_update(request):
	
	cart = Cart(request)
	if request.POST.get('action') == 'post':
		# Get stuff
		product_slug = request.POST.get('product_slug')
		product_qty = int(request.POST.get('product_qty'))

		#product = get_object_or_404(Product, PRDSlug=product_slug)

		cart.update(product=product_slug, quantity=product_qty)

		response = JsonResponse({'qty':product_qty})
		#return redirect('cart_summary')
		return response

cart/templates/cart_summery.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<!-- Section-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Cart</h1>
            <p class="lead fw-normal text-white-50 mb-0">Explore Your Cart Section</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">

    <div class="container px-4 px-lg-5 mt-5">

        {% if cart_products %}

        <div class="small-container cart-page">
                <table>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                     {% for product in cart_products %}
                    <tr>
                        <td>
                            <div class="cart-info">
                            {% if product.PRDImage %}
                                <img src="{{product.PRDImage.url}}">
                            {% else %}
                                <img src="{% static "img/no image.jpg" %}">     
                            {% endif %}
                                <div>
                                    <p style="font-size: 20px;">{{product}}</p>
                                    <small style="font-size: 20px;">Price: ${{product.PRDPrice}}</small>
                                    <br><br>
                                    <a href="{% url 'cart:cart_delete' product.PRDSlug %}" class="btn btn-outline-dark mt-auto">Delete</a>
                                    <a href="#" class="btn btn-outline-dark mt-auto update-cart" data-index="{{ product.PRDSlug }}">Update</a>


                                </div>
                            </div>
                        </td>
                        <td><div class="col-md-6">
                         <select class="form-select form-select-sm" id="select{{product.PRDSlug }}">
                  
                                {% for key, value in quantity.items %}
                                    {% if key == product.PRDSlug  %}
                                <option selected>{{ value }}</option>
                                    {% endif %}
                                {% endfor %}
                                               

                                  <option value="1">1</option>
                                  <option value="2">2</option>
                                  <option value="3">3</option>
                                  <option value="4">4</option>
                                  <option value="5">5</option>
                                  <option value="6">6</option>
                                  <option value="7">7</option>
                                  <option value="8">8</option>
                                  <option value="9">9</option>
                                  <option value="10">10</option>
                                  <option value="11">11</option>
                                  <option value="12">12</option>
                                
                            </select>
                            </div>
                        </td>
                        {% for key, value in  single_total_price.items%}
                            {% if key == product.PRDSlug  %}
                            <td>Total Price: ${{value}}</td>
                            {% endif %}

                            
                        {% endfor %}
                        
                    </tr>
                    {% endfor %}
                    
                </table>
                <div class="total-price">
                    <table>
                        
                        
                        <tr>
                            <td>Total</td>
                            <td>${{ all_total_price }}</td>


                        </tr>


                    </table>

                  

                </div>
                <br><br><br>
             <div class="d-flex justify-content-center">
                <a href="{% url 'order:confirmed_order' %}" class="btn btn-outline-dark">CheckOut</a>
             </div>               


                {% else %}
               <h2> There Is Nothing In Your Cart Yet .......</h2>
               <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


            {% endif %}
    
        </div>
 
</section>


<h1> </h1>




<script>
$(document).on('click', '.update-cart', function(e){
    e.preventDefault();
    
    var productSlug = $(this).data('index');

    $.ajax({
        type: 'POST',
        url: '{% url 'cart:cart_update' %}',
        data: {
            product_slug: productSlug,
            product_qty: $('#select' + productSlug + ' option:selected').text(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
        },
        success: function(json){
            location.reload();
        },
        error: function(xhr, errmsg, err){
            // Handle error if needed
        }
    });
});


</script>

	
{% endblock body %}