accounts/urls.py
from django.urls import path 
from . import views




app_name='accounts'



urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile/<slug:slug>',views.profile,name='profile'),
    path('profile/<slug:slug>/edit' ,  views.profile_edit , name='profile_edit'),

]

cart/urls.py
from django.urls import path 
from . import views




app_name='cart'



urlpatterns = [
    path('',views.cart_summery,name='cart_summery'),
    path('add/',views.cart_add,name='cart_add'),
    path('delete/<str:product_slug>',views.cart_delete,name='cart_delete'),
    path('update/',views.cart_update,name='cart_update'),
    
  

    
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("admin/", admin.site.urls),

    path("", include('store.urls', namespace='store') ),
    
    
]




urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path 
from . import views




app_name='store'



urlpatterns = [
    path('',views.product_list,name='home'),
    path('<slug:slug>',views.product_detail,name='product_detail' ),
    path('category/<slug:slug>',views.category_detail,name='category_detail' ),

    
]

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>E Store</title>
    <link rel="shortcut icon" style="width: 50px; height: 50px;" type="image/x-icon" href="{% static "images/logo.jpg" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{%static 'css/normalize.css'%}"/>
    <link rel="stylesheet" href="{%static 'css/styles.css'%}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

</head>

<nav class="navbar sticky-top navbar-light navbar-expand-lg ">
    <div class="container">
  <a class="navbar-brand" href="/"><img src="{%static 'images/logo.jpg'%}" style="width: 150px; height: 100px;"/></a>

<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"> </span>
      <span class="icon-bar" style="color:red"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <div class="navbar-nav ms-auto">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">All Category</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url "store:home" %}">All Category</a></li>
                <li><hr class="dropdown-divider" /></li>
                {% for category in categories  %}
                <li><a class="dropdown-item" href="{{category.get_absolute_url}}">{{category}}</a></li>
                {% endfor %}
            </ul>
        </li>




      <a class="nav-item nav-link" href="#">Contact US </a>

      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle"></i>  Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url "accounts:profile" slug=request.user.username|lower %}"> {{ request.user.username }}'s Profile</a>
                <a class="dropdown-item" href="{% url "accounts:profile_edit" slug=request.user.username|lower %}">Edit My Profile</a>
                <a class="dropdown-item" href="{% url "password_change" %}">Change Password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">My Orders</a>
                <a class="dropdown-item" href="#">Track Order</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link border border-light rounded waves-effect">
            <i class="fas fa-sign-in-alt mr-2"></i>Login
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:signup' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fas fa-user-plus"></i>Signup
            </a>
            </li>
        {% endif %}
    </ul>

        </li>



        
        
        
        <a class="nav-item nav-link" href="/"> <i class="fa-solid fa-cart-shopping"></i> </a>
        
</div>
    </div>
  </div></div>
</nav>

<body>

{%block body  %}


{%endblock body %}






<footer>
<div class="footer" style="background:url({%static 'images/footer-banner.png'%});position: relative;">
<div class="container footer-container p-0">

    <div class="footer-row row">
    <div class="footer-col col-md-3"><div class="text-center">
        <img src="{%static 'images/logo.jpg'%}" style="width: 150px; height: 120px; padding-bottom:28px;"/></div>
        <p class="footer-about "> BD-Ebook Buy your favorite books online without any hassle.</p>
        <p class="social-icons"><i class="fa-brands fa-facebook fa-2x"></i> <i class="fa-brands fa-twitter fa-2x"></i>  <i class="fa-brands fa-instagram fa-2x"></i>  <i class="fa-brands fa-youtube fa-2x"></i>  <i class="fa-brands fa-discord fa-2x"></i> </p>

    </div>
    <div class="footer-col col-md-3">
    <ul class="footer-useful list-unstyled"> Useful Links
        <hr>
         <li > <a class="footer-link text-decoration-none" href="/"> Home </a> </li>
         <li><a class="footer-link text-decoration-none" href=""> Account </a> </li>
         <li > <a class="footer-link text-decoration-none" href=""> Orders </a> </li>

    </ul>
    </div>
    <div class="footer-col col-md-3">
    <ul class="footer-useful list-unstyled"> About
    <hr>
        <li><a class="footer-link text-decoration-none" href="#"> About Us </a> </li>
        <li><a class="footer-link text-decoration-none" href="#" > Contact Us </a></li>

    </ul>
    </div>
    <div class="footer-col col-md-3">
    <h6 class="footer-useful"> Payment Methods </h6> <p class="footer-about ">
    <hr>
    <img src="{%static 'images/pay-us.png'%}" style="height:36px;"/>
    </div>

    </div>

</div>


</div>

<div class="footer-copyright" style="background: #444444;height:40px">

    <div class="row" style="height: 38px;">
        <p class="footer-copyright-text text-center"> Template Copyright 2022 by Siam All right reserved. </p>
    </div>
</div>




        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</footer>
</body>

</html>